function routingmap = import_routing_map_txt(filename)
%IMPORTFILE Import data from a text file
%  ROUTINGMAP = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a string array.
%
%  ROUTINGMAP = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  routingmap = importfile("/media/autobuntu/chonk/chonk/git_repos/Van_Apollo_GPS_Handler/MATLAB_Scripts/Raw_Routes/ohio_athens_blue_v1/routing_map.txt", [5, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 19-Jan-2023 16:49:39

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["lane_id", "VarName2", "VarName3"];
opts.VariableTypes = ["string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["lane_id", "VarName2", "VarName3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["lane_id", "VarName2", "VarName3"], "EmptyFieldRule", "auto");

% Import the data
routingmap = readmatrix(filename, opts);

end